<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKhbx0hg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKhbx0hg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKhbx0hg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKhbx0hg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKhbx0hg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Khbx0hg',
    'container.build_id' => 'f3e2c77b',
    'container.build_time' => 1617721260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKhbx0hg');
