<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1VLQmzP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1VLQmzP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1VLQmzP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1VLQmzP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1VLQmzP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1VLQmzP',
    'container.build_id' => '7ff1c06d',
    'container.build_time' => 1618247595,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1VLQmzP');
