<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6kBuUQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6kBuUQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ6kBuUQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ6kBuUQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ6kBuUQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z6kBuUQ',
    'container.build_id' => 'dbe41ac0',
    'container.build_time' => 1619019816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6kBuUQ');
